DROP TABLE IF EXISTS offline_payments CASCADE;
DROP TABLE IF EXISTS fee_plans CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS student_fees CASCADE;
DROP TABLE IF EXISTS fee_structures CASCADE;
DROP TYPE IF EXISTS fee_status CASCADE;
DROP TYPE IF EXISTS payment_cycle CASCADE;
